.\"     Title: yasss\-curses
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 
.\"    Manual: 
.\"    Source: 
.\"
.TH "yasss\-curses" "1" "" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH ""
YasSS\-curses \- Yet another (simple|stupid) Sudoku Solver \- play Sudoku
.SH ""
\fIyasss\fR.sp
.SH "DESCRIPTION"
YasSS\-curses generates a random Sudoku on startup and presents you a nice textual interface to solve it..sp
.SH "KEY BINDINGS"
.PP
\fIh\fR, \fILEFT\-ARROW\fR
.RS 3n
Move Cursor to the left.
.RE
.PP
\fIl\fR, \fIRIGHT\-ARROW\fR
.RS 3n
Move Cursor to the right.
.RE
.PP
\fIj\fR, \fIDOWN\-ARROW\fR
.RS 3n
move Cursor down.
.RE
.PP
\fIk\fR, \fIUP\-ARROW\fR
.RS 3n
move Cursor up.
.RE
.PP
\fI1\fR \&... \fI9\fR
.RS 3n
Enter the pressed number.
.RE
.PP
\fI0\fR, \fIDEL\fR, \fId\fR
.RS 3n
Delete the current number.
.RE
.PP
\fIL\fR
.RS 3n
Toggle the
\fIlocked\fR\-flag for the number under the cursor. Locked numbers cannot be changed and are displayed in bold white.
.RE
.PP
\fIH\fR
.RS 3n
Give a hint: enter the correct number at the cursor position.
.RE
.PP
\fIc\fR
.RS 3n
Check Sudoku for correctness. Displays a message if it is correct or not.
.RE
.PP
\fIC\fR
.RS 3n
Like
\fIc\fR, except that it hilights all wrong numbers
.RE
.SH "BUGS"
.TP 3n
\(bu
If called twice a second it generates the same Sudoku due to the way the random number generator is initialized
.TP 3n
\(bu
Wrong numbers under the cursor are not hilighted when
\fIC\fR
is pressed.
.TP 3n
\(bu
Some keys are processed wrong if modifies (shift, control\&...) are pressed.
.SH "AUTHOR"
Written by Moritz Andreas Lenz, <moritz@faui2k3.org>.sp
.SH "RESOURCES"
Project page: http://moritz.faui2k3.org/yasss.sp
Google Code project page: http://code.google.com/p/yasss.sp
More on Sudoku: http://moritz.faui2k3.org/sudoku.sp
.SH "COPYING"
Copyright (C) 2006 Moritz Andreas Lenz. Free use of this software is granted under the terms of the GNU General Public License (GPL) or under the Artistic License. See the file LICENSE for details..sp
